name: "iOS CI Workflow"

on:
  push:
    branches:
      - ci-test
  pull_request:
    branches:
      - ci-test

jobs:
    build-test:
        runs-on: macos-15
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
    
            - name: Set up Xcode
              run: |
                sudo xcode-select -s /Applications/Xcode_16.4.0.app
    
            - name: Cache SwiftPM
              uses: actions/cache@v4
              with:
                  path: ~/Library/Developer/Xcode/DerivedData/SourcePackages
                  key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
                  restore-keys: ${{ runner.os }}-spm-
    
            - name: Resolve dependencies
              run: xcodebuild -resolvePackageDependencies -scheme "Wallet"
              
            # - name: Build
            #   run: xcodebuild build \
            #     -scheme "Wallet" \
            #     -sdk iphonesimulator \
            #     -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.5'
      
            - name: Test
              run: |
                xcodebuild test \
                  -scheme "Wallet" \
                  -sdk iphonesimulator \
                  -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.5' \
                  -skip-testing:WalletUITests
